### ISSUE TITLE
Fix sidewalk tagging

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#126]
Based on [the sidewalk analysis happening over on #125](https://github.com/mapbox/mapping/issues/125) we should fix tagging them. Use [osm-sidewalker](https://www.mapbox.com/osm-sidewalker/) identify and fix all `highway=footway` that are sidewalks or crosswalks which are not tagged in OpenStreetMap.

- Add [`footway=sidewalk`](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dsidewalk) to `highway=footway` that are sidewalks either separated by grass patch or attached to the associated highway.
- Add [`footway=crossing`](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing) to `highway=footway` where `footway` crosses highways.

### Task Workflow
Updated mapping instructions are  [documented here](https://github.com/mapbox/mapping/issues/126#issuecomment-159849522)

**Comment by lxbarth** [comment]
Let's be careful with [adding a `footway=sidewalk` tag to a `highway=footway` that contains a sidewalk relation to a road](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dsidewalk#Use_of_a_relation_.28optional.29) - it may not be established mapping practice.

**Comment by tcql** [comment]
I've got a slippy map of New York, DC, California, and Germany using the current logic [here](https://api.mapbox.com/styles/v1/tcql/ciftz3vmh0015tgkpfyy0rn4l.html?title=true&access_token=pk.eyJ1IjoidGNxbCIsImEiOiJaSlZ6X3JZIn0.mPwXgf3BvAR4dPuBB3ypfA#9.73/40.6906/-73.9828)

@planemad can you take a look at this and see if you can do anything with it? Let me know how you think we could improve our sidewalk detection, and if there's anything I could do to improve the map / how we share this information

**Comment by planemad** [comment]
@tcql looks great. Was digging through this and have some observations:

- Motorways don't have sidewalks, so its pretty easy to drop these false positives.
![screenshot 2015-10-19 17 17 18](https://cloud.githubusercontent.com/assets/126868/10577029/5c8c7e10-7685-11e5-9c69-36305e9c47f5.png)
- Most false positives seem to be in leisure areas like parks, stadiums and around lakes. These areas usually have detailed footways and the chance of a false positive is much higher, Maybe they should be dropped too?
![screenshot 2015-10-19 17 46 34](https://cloud.githubusercontent.com/assets/126868/10577504/6428b338-7689-11e5-990f-4220eabdba9e.png)
![screenshot 2015-10-19 17 32 23](https://cloud.githubusercontent.com/assets/126868/10577285/87936798-7687-11e5-8e90-e608179c3fcc.png)
![screenshot 2015-10-19 17 35 36](https://cloud.githubusercontent.com/assets/126868/10577308/f04de57e-7687-11e5-8029-292573525bef.png)
![screenshot 2015-10-19 17 38 38](https://cloud.githubusercontent.com/assets/126868/10577349/44a224f0-7688-11e5-866c-2cefd780ac25.png)
- Other obvious false positives
![screenshot 2015-10-19 17 42 18](https://cloud.githubusercontent.com/assets/126868/10577418/c833fbd6-7688-11e5-8c32-cac7bb78e6a6.png)
- Footways that actually require sidewalk tag seem to come up in clusters, where a particular mapper might have done micro mapping.
![screenshot 2015-10-19 17 11 18](https://cloud.githubusercontent.com/assets/126868/10577385/7f1ab2be-7688-11e5-8d29-221b98a60a8e.png)
![screenshot 2015-10-19 17 11 50](https://cloud.githubusercontent.com/assets/126868/10577386/7f77c3fa-7688-11e5-927a-4d6c8b82d457.png)
![screenshot 2015-10-19 17 44 08](https://cloud.githubusercontent.com/assets/126868/10577455/07ab1a42-7689-11e5-9e42-779360659477.png)
![screenshot 2015-10-19 17 45 24](https://cloud.githubusercontent.com/assets/126868/10577476/3243d24e-7689-11e5-96c3-b744c7f77417.png)
![screenshot 2015-10-19 17 51 24](https://cloud.githubusercontent.com/assets/126868/10577581/0e4d8e10-768a-11e5-815c-9eb9e700b979.png)
- Multiple parallel footways is a sure sign that some of them need secondary tags
![screenshot 2015-10-19 17 52 31](https://cloud.githubusercontent.com/assets/126868/10577627/69698d8a-768a-11e5-80c8-ad5a6d4d4dae.png)

**Summary**
- Overall i'm seeing a lot of false positives and a majority of them are footways in leisure areas and open spaces. There are probably a few legitimate cases in there but looks like we can drop them
- Wether a footways is a sidewalk can sometimes be detected visually by seeing the arrangements of all footways in the vicinity. Some subtle coloring for other footways can help investigate these patterns further
- The most actionable areas are those with a large number of hits. These seems to be neighborhoods of micro mapping and allows us to make many more fixes in single sweep. In the initial phase I think this is where our focus should be rather than fixing stray sidewalks one by one.
- The workflow to do this task as a team is currently not very effective. For starters we need a single click way to open the map location into JOSM.

**Comment by tcql** [comment]
@planemad thanks! I'll hit as much of this this morning as I can

> Motorways don't have sidewalks

:+1: removing motorways

> Overall i'm seeing a lot of false positives and a majority of them are footways in leisure areas 

That's tough to narrow in on -  roads can cut through leisure areas, or run along the edges and have their sidewalks marked inside the park area
<img width="229" alt="screen shot 2015-10-19 at 9 34 40 am" src="https://cloud.githubusercontent.com/assets/348805/10579181/b8c0cdb2-7644-11e5-8919-849f4bfa4104.png">

I'll see if there's some way to tighten this without excluding everything. If this turns out to be a big issue, we could just exclude footways in leisure areas from the search, and hit the obvious ones elsewhere for now.

> Wether a footways is a sidewalk can sometimes be detected visually by seeing the arrangements of all footways in the vicinity. Some subtle coloring for other footways can help investigate these patterns further

Color all footways, subtly marking which are sidewalks, which are paths, etc?

> The workflow to do this task as a team is currently not very effective. For starters we need a single click way to open the map location into JOSM.

I'll look into this today

**Comment by planemad** [comment]
> I'll see if there's some way to tighten this without excluding everything. If this turns out to be a big issue, we could just exclude footways in leisure areas from the search, and hit the obvious ones elsewhere for now.

What could quickly help is highlighting parks and water areas on the map. That way its easier to investigate them visually on the map which is effective in taking a decision.

> Color all footways, subtly marking which are sidewalks, which are paths, etc?

:+1: nothing too drastic. I feel the eye might be able to spot odd patterns more easily this way.

> For starters we need a single click way to open the map location into JOSM.

Just remembered theres a great hack by @geohacker which could help: http://geohacker.in/unconnected-tiger/

It uses surface API to get the osm_id of the object clicked in a Mapbox dataset and loads it into JOSM using remote control. If you could quickly port it to gl-js that would be perfect.

**Comment by tcql** [comment]
@planemad 

<img width="879" alt="screen shot 2015-10-19 at 6 14 37 pm" src="https://cloud.githubusercontent.com/assets/348805/10592933/77a0044e-768d-11e5-8453-d117f42183eb.png">

Build a little prototype [here](https://tcql.github.io/maps/sidewalks.html)

- show parks
- show water
- exclude motorways from sidewalk checking
- supports click to view data, & a button to open in JOSM

I'm running a tile-reduce job for the whole US which should be complete later tonight, and then I'll update the map style

**Comment by planemad** [comment]
@tcql :+1: beautiful!

**Comment by tcql** [comment]
updated map with the continental US

<img width="926" alt="screen shot 2015-10-20 at 9 34 04 am" src="https://cloud.githubusercontent.com/assets/348805/10608864/fbbfc652-770e-11e5-9aa7-84c474a31841.png">

**Comment by maning** [comment]
Per voice with @srividyacb and @jinalfoflia, we will run a couple of test cases today and Friday using @tcql's map.  To easily monitor discussion, all encountered false positives will posted in #125.
Discussion on the final workflow will be here.

**Comment by maning** [comment]
[WIP] Workflow for sidewalk tagging

@srividyacb  and @jinalfoflia is currently testing @tcql's map to fix sidewalks and flag false-positives.
For easy tracking, false positives will be reported at #125. This is to improve the detection of sidewalks.

However, on our initial pass today, we think that working on each detected way would be too onerous.
The best way is to assign people to work on a larger area and fix it in one go. This allows the team member to look into the general context of the area and easily tag connected ways.

### Sketch Workflow
1. @tcql will prepare another layer showing the density of errors at z15 or z16 grid, this can either be using kernel density or convex hull in turf.js.  Add a JOSM RC button to download data within the grid
2. Each person will be assigned an area say DC grids. 
2. In JOSM, download data within the assigned grid. 
3. Add an inverse filter for all footways, ie. `user:username AND highway=footway`
4. Use JOSM's todo plugin to work on each highway=footway and add appropriate tags.
5. Upload and move on to the next grid

@tcql, will run a daily update so we can visualize what needs work by next day.
We will test this workflow by Friday here in @mapbox/india-office 
cc @planemad @lxbarth @Rub21

**Comment by maning** [comment]
Whitelist `foot=yes; highway=cycleway`.  See: https://www.openstreetmap.org/way/25964014/

**Comment by tcql** [comment]
- [ ] Set up daily runs
- [ ] Hook daily runs into interactive map
- [ ] build density grid

Got hung up on other things the past few days, tonight is my test run for the daily cron script, and tomorrow I should get the density grid worked out.

**Comment by maning** [comment]
@tcql, we tried adding your map as background image in JOSM, but it doesn't show your [glowing green style](https://a.tiles.mapbox.com/v4/tcql.usa-sidewalks/14/4827/6155.png?access_token=pk.eyJ1IjoidGNxbCIsImEiOiJaSlZ6X3JZIn0.mPwXgf3BvAR4dPuBB3ypfA).

**Comment by maning** [comment]
@lxbarth Before going full steam with the [above workflow](https://github.com/mapbox/mapping/issues/126#issuecomment-149917473), should we first inform the talk-us community? Especially since sidewalk tagging is tricky and there is no consensus within the list.

**Comment by maning** [comment]
> we first inform the talk-us community? 

Done. Waiting for community discussion.

**Comment by tcql** [comment]
@maning I moved the final location of the interactive map to [OSM Sidewalker](https://mapbox.com/osm-sidewalker/). This supports selecting z15 tiles and opening them with segments selected in JOSM, as well as opening individual segments in iD

**Comment by RicoElectrico** [comment]
Is it possible to get that map in an international version?
(on a side note, it's funny how USA is assumed implicit at Mapbox and others. Reminding you that there is world beyond the States :stuck_out_tongue: - please consider this for all your other activities and development.)

**Comment by tcql** [comment]
@RicoElectrico definitely! It's on the list. We started in the US intentionally because some other areas tend to follow other types of tagging, and so we could have a good basis to start from

**Comment by maning** [comment]
![sidewalk](https://cloud.githubusercontent.com/assets/353700/10778887/3af4b908-7d50-11e5-9726-fbdbb62f539c.gif)

@tcql Excellent! Tile download is really helpful. To recap our workflow: 

1. Select a red tile in the map. Click, **Open in JOSM**.
2. Add the selected sidewalks in JOSM's **Todo list**.
3. Review and add `footway=sidewalk`.
4. Click **Mark** and move to the next in the list.
5. Upload to OSM with the changeset comment: `#Sidewalk tagging. Project part of https://github.com/mapbox/mapping/issues/126`

**Comment by maning** [comment]
### 2015-10-30
Working on 3 states to benchmark effort
* @srividyacb - Texas
* @jinalfoflia - California
* @chtnha - New York

@tcql @lxbarth @planemad

**Comment by srividyacb** [comment]
### 2015-11-02

Today, we came across lot of fixed sidewalk from Friday. 

* @srividyacb - Texas - http://overpass-turbo.eu/s/cmX
* @jinalfoflia - California http://overpass-turbo.eu/s/cn0
* @chtnha - New York http://overpass-turbo.eu/s/cn2
* @maning - North Carolina http://overpass-turbo.eu/s/cq5

@tcql @lxbarth @planemad

**Comment by tcql** [comment]
@srividyacb thanks, I'm working out some issues with automatically updating the map. should have it sorted out today so we can see proper updates

**Comment by srividyacb** [comment]
@tcql 
In sidewalk detection we are getting some places where `highway=footway` is also having `area=yes` tag. 

![footway](https://cloud.githubusercontent.com/assets/3423533/10932619/251c730c-82f8-11e5-8449-b9930bc989ae.gif)

Also there are `highway=footway` with a `tunnel=yes` tag. These should not be highlighted to mark as `footway=sidewalk` because they don't run alongside of main highways. 

![tunnel](https://cloud.githubusercontent.com/assets/3423533/10932693/d8299c0e-82f8-11e5-922a-af2aec230804.gif)

Link to the area: https://www.openstreetmap.org/#map=15/29.75993/-95.36531

**Comment by tcql** [comment]
just FYI to @RicoElectrico and anybody else wondering, international [sidewalk detection is up on the interactive page](https://mapbox.com/osm-sidewalker) now.

Daily updates are still stalled at the moment (particularly because we're working on some tweaks to tile-reduce and OSM QA tiles). I'm occasionally running manual updates. Some tweaks to improve false-positive matching are going to go in today and we should have a fresh update by tomorrow.

**Comment by jinalfoflia** [comment]
@tcql we came across quite a few sidewalks with the `bicycle=yes` and `name` tags. In the talk-us mailing list, they have discussed that [named footways are not sidewalks](https://lists.openstreetmap.org/pipermail/talk-us/2015-October/015594.html). It would be great if we could eliminate them while processing itself.

/cc @maning @srividyacb

**Comment by maning** [comment]
> we came across quite a few sidewalks with the bicycle=yes and name tags

Here's the running list of secondary tags that should be excluded: https://github.com/mapbox/mapping/issues/125#issuecomment-157022204

**Comment by jinalfoflia** [comment]
#### Sidewalk tagging report

- Till date there are 1,37,875 ways which are tagged with `footway=sidewalk` and `footway=crossing`.
![screenshot 2015-11-25 11 48 20](https://cloud.githubusercontent.com/assets/4470913/11389968/6ac5eee6-936b-11e5-829e-867060703586.png)
-  @maning , @chtnha , @srividyacb and @jinalfoflia have been working on tagging missing sidewalks and crossings in the US and have tagged 3,146 ways.

    * @srividyacb - http://overpass-turbo.eu/s/cUP
    * @maning  - http://overpass-turbo.eu/s/cUT
    * @chtnha  - http://overpass-turbo.eu/s/cUU
    * @jinalfoflia - http://overpass-turbo.eu/s/cUV

- The team also was involved in recognising false positives in sidewalk detection and improving the detection process with @tcql 

#### Next Action[s]
Our goal is to complete tagging of missing sidewalks in the US region by the end of the coming week.
- [ ] We want @mapbox/india-office to join hands in completing this task.
- [ ] Let's work on sidewalk-tagging this Thursday [26 Nov 2015].
- [ ] Tomorrow @srividyacb and myself will be giving an introduction on `sidewalk tagging` to the entire team.

/cc @planemad @maning @srividyacb @tcql @lxbarth @shvrm

**Comment by tcql** [comment]
@jinalfoflia thanks for writing this up! I'll make sure to push an update with the latest version of the map today to eliminate as many false positives as possible

**Comment by srividyacb** [comment]
As the [osm-sidewalker](https://www.mapbox.com/osm-sidewalker/) is not working for the bounding box and team is finding it difficult to work, we have pinged @tcql on this and we will start the sidewalk tagging as soon as it gets fixed.

**Comment by srividyacb** [comment]
#### Overview

Use [osm-sidewalker](https://www.mapbox.com/osm-sidewalker/) to fix `highway=footway` with [`footway=sidewalk`](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dsidewalk) and [`footway=crossing`](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing) tags.

We need to identify and fix all `highway=footway` that are sidewalks or crosswalks which are not tagged in OpenStreetMap.

### [Sketch Workflow](https://github.com/mapbox/mapping/issues/126#issuecomment-149917473)

1. Each person will be assigned an area.
2. Click on highlighted area on the [map](https://www.mapbox.com/osm-sidewalker/) and download the data to JOSM.
3. Add the sidewalk layer in JOSM to verify the sidewalks detected before tagging:
tms url `tms:https://{switch:a,b,c}.tiles.mapbox.com/v4/tcql.usa-sidewalks/{zoom}/{x}/{y}.png?access_token=pk.eyJ1IjoidGNxbCIsImEiOiJaSlZ6X3JZIn0.mPwXgf3BvAR4dPuBB3ypfA`
4. Use [JOSM's todo plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/TODO_list) to work on each highway=footway and add appropriate tags.
5. Upload and move on to the next grid. 

**Changeset comment:** `#Sidewalk tagging. Project part of https://github.com/mapbox/mapping/issues/126 `
**Source**: `Bing/Mapbox`

#### Filters to use
- Add an inverse filter for all generic footways, ie. `type:way highway=footway -(footway=sidewalk | footway=cycleway | footway=crossing)`
- `highway=footway | name=*` : Highlights all the footways
- `footway=crossing` : Hides all the `footway=crossing` tagged footways once added.
- `footway=sidewalk` : Hides all the `footway=sidewalk` tagged footways once added. 
- You can switch between filters to hide/show the ways and add tags correctly and change the incorrect tags.

#### Do's and Dont's
- Let's be careful with [adding a `footway=sidewalk` tag to a `highway=footway` that contains a sidewalk relation to a road](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dsidewalk#Use_of_a_relation_.28optional.29) - it may not be established mapping practice.
- Don't add a sidewalk tag to the footways which have names to it ( Filter: `highway=footway | name=*`)
- If a footway is having a `bicycle=yes` tag, we will be adding the `footway=sidewalk` tag if it's a sidewalk as per the imagery. **Don't remove `bicycle=yes` tags**
- We won't add `sidewalk` tag to the `highway=cycleway`
- Don't align or extend the existing footways.
- The sidewalk detection algorithm has already removed false positives like `tunnels`, `cycleways`, ``highway=footway with area=yes`` and other possible tags in the process. If you come across tags like that ignore them.

![sidewalk_tag](https://cloud.githubusercontent.com/assets/353700/10661292/9af41518-78ca-11e5-8522-aeaf3719cd0b.gif)

cc @planemad @lxbarth @maning cc @mapbox/india-office

**Comment by tcql** [comment]
Quick update on the tile-reduce side: I'll be working to get an automated solution using scheduled Autoscaling, so we can run sidewalk analysis daily. Stats will [be posted here](https://github.com/mapbox/osm-sidewalker/blob/stats/README.md)

cc @maning @srividyacb

**Comment by lxbarth** [comment]
@tcql fyi, only US needed for now in case this is much faster to set up for US than for entire world.

**Comment by nickidlugash** [comment]
Per chat with @lxbarth, it looks like DC could use a bit of clean-up, as we're seeing some small fragments of footpaths that should maybe be tagged as sidewalks. E.g.:

![screen shot 2015-12-04 at 7 12 37 pm](https://cloud.githubusercontent.com/assets/5607844/11604502/637fb368-9abb-11e5-841a-7437b631f77c.png)
http://www.openstreetmap.org/edit?pk_campaign=mapbox-edit#map=21/38.88771/-77.01634

and 

![screen shot 2015-12-04 at 7 04 11 pm](https://cloud.githubusercontent.com/assets/5607844/11604506/6d954b1a-9abb-11e5-9043-9ad74069b838.png)
http://www.openstreetmap.org/edit?pk_campaign=mapbox-edit#map=19/38.89729/-77.01196

/cc @srividyacb @maning @chtnha @jinalfoflia

**Comment by planemad** [comment]
@tcql we don't have a good way to measure our progress on the sidewalks:
- We currently manually assign areas to team members, but this is not scalable in the long run or coordinate tasks with the community.  If blocks that have been edited are highlighted in a different color it would help skip areas that have been fixed.
- The analysis includes a significant portion of false positives. This makes it hard to estimate at what point the task is complete. If there is a way to rank the detected sidewalks with some score, it will help focus our efforts much better to fix the easiest ones faster and on a larger scale.

cc @shvrm @srividyacb @maning

**Comment by planemad** [comment]
Proposed sidewalk rendering on [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/issues/1998)

**Comment by tcql** [comment]
> We currently manually assign areas to team members, but this is not scalable in the long run or to coordinate tasks with the community. If blocks that have been edited are highlighted in a different color it would help skip areas that have been looked into previously

@planemad It might be possible to use a dataset to store features (selected tiles), like the [Chennai Flood Map](https://github.com/osm-in/flood-map) and then load that dataset on the frontend. I'll look into it.

> The analysis includes a significant portion of false positives. This makes it hard to estimate at what point the task is complete. If there is a way to rank the detected sidewalks with some score, it will help focus our efforts much better to fix the easiest ones faster and on a larger scale.

Yea, I get that this is difficult. We could possibly use a level of variation in the distance from the road along a segment to score it's likelihood to be a sidewalk. [I ticketed this on osm-sidewalker](https://github.com/mapbox/osm-sidewalker/issues/11)

**Comment by planemad** [comment]
> It might be possible to use a dataset to store features (selected tiles), like the Chennai Flood Map and then load that dataset on the frontend. I'll look into it

@tcql this would be great. The use case to know if someone has looked into a tile is pretty common for similar mapping analysis and tile reduce based tasks that we can run in the future and is well worth the effort.

**Comment by srividyacb** [comment]
@mapbox/india-office 

Here is the top cities which we need to hit for sidewalks. Assign a city from top for yourself and clean it. Work in pair if its a big city. 

https://textb.org/t/Sidewalk/.

**Comment by nickidlugash** [comment]
So excited to see this continued work on sidewalks! I'm happy to help do some reviews after clean up, especially for the cities I've lived in (DC, Boston, Philadelphia).

**Comment by planemad** [comment]
@nickidlugash are you doing the review using the Strava style? It would be nice to have a style specifically to do QA and help visually spot any glaring tagging issues.

Tried this out with [this style](https://api.mapbox.com/styles/v1/planemad/cihyukica00wdbnm3wglrc651.html?title=true&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#15.28/38.8986/-77.0234) to differentiate footway, sidewalks and crossings:

<img width="294" alt="screenshot 2015-12-10 10 42 23" src="https://cloud.githubusercontent.com/assets/126868/11707451/c586b318-9f2a-11e5-86bf-fda9b0e5aa44.png">
This helped spot a bunch of incorrect tagging, like these sidewalk tagged as a crossing.

**Comment by ramyaragupathy** [comment]
I have been working on sidewalk tagging in Denver city with [this workflow](https://gist.github.com/ramyaragupathy/16609e902ed48cbe61d1). This helps me set a reference and a sense of where the work is happening within a city.

**Comment by srividyacb** [comment]
OSM Diary post up: https://www.openstreetmap.org/user/srividya_c/diary/37594

No actions here. Closing

**Comment by tcql** [comment]
thanks everybody who ran on this :+1: this is some *seriously awesome work*. It's been awesome watching the stats on this and seeing the massive progress everybody made.

I would love to revisit the tooling in the future and implement [some of the ideas here](https://github.com/mapbox/mapping/issues/126#issuecomment-163092809) to improve this. I also believe we can definitely improve matching and remove more false positives so the community can run with this and keep making OSM better

**Comment by RobJN** [comment]
Are you marking false positives so they are hidden from the slippy map? Or is it just a case of remembering where you have already looked?
