### ISSUE TITLE
[SF Buildings] Tracing buildings in San Francisco Peninsula

### ISSUE THREAD

**Issue by srividyacb** [mapbox/mapping#141]
**Objective:** Add missing building footprints in SF Peninsula

Prior Tasks: https://github.com/mapbox/mapping/issues/135 https://github.com/mapbox/mapping/issues/136

<img width="337" alt="screenshot 2015-11-23 11 49 18" src="https://cloud.githubusercontent.com/assets/126868/11330842/3f4c772e-91d8-11e5-8da2-bd11f0277ac7.png">
**Focus Area**: [1290 sq.km](https://gist.github.com/732acea19b0336e418d0)
**Estimates**: [~1,79,000 buildings](https://github.com/mapbox/mapping/issues/141#issuecomment-160596321)
**Duration**: **[18 days](https://github.com/mapbox/mapping/issues/141#issuecomment-160604840)**
**Progress**: [173447 buildings](https://github.com/mapbox/mapping/issues/141#issuecomment-164547016)

**Open Datasets availability** : **[Overview](https://github.com/mapbox/mapping/issues/141#issuecomment-161639335)**

Team: @mapbox/india-office and @mapbox/peru-office 

#### Mapping Sources
Source | Description|Quality|License 
---|---|---|---
Mapbox Satellite | Imagery | High |:white_check_mark: 
Bing Imagery | Imagery | High | :white_check_mark: 
[Mountain View](http://data.mountainview.opendata.arcgis.com/datasets/da645ec14de042bdb3297ee1be6c6fcd_0) and [Palo Alto](https://www.google.com/fusiontables/DataSource?docid=1r-wrSG94TjWWCJVB79B6F_BkYK1-ar0SCyq0AkQM#rows:id=1) | Building Footprints| High | :grey_question: 

#### Subtasks

Tasks | Description|Start|End(ETA)|Validation
---|---|---|---|---|
[Mountain View](http://tasks.openstreetmap.us/project/9) | [Adding buildings](https://github.com/mapbox/mapping/issues/136) |11/17 | 11/24|[Completed](https://github.com/mapbox/mapping/issues/136#issuecomment-162846008)
[Menlo Park](http://tasks.openstreetmap.us/project/11) | [Adding buildings](https://github.com/mapbox/mapping/issues/135) |11/25 |12/03 |[Completed](https://github.com/mapbox/mapping/issues/135#issuecomment-161922079)
[Missing Buildings](http://tasks.openstreetmap.us/project/12) | [Adding buildings](https://github.com/mapbox/mapping/issues/136) |12/04 |12/28 |Completed
[Missing Buildings in SF Peninsula](http://tasks.openstreetmap.us/project/14)|[Adding buildings](https://github.com/mapbox/mapping/issues/136)|01/04|01/06|Completed|
[Filling gaps in SF Bay](http://tasks.openstreetmap.us/project/15)|[Adding buildings](https://github.com/mapbox/mapping/issues/136)|01/08|01/18|Completed|
[Palo Alto/Cupertino import cleanup](http://tasks.openstreetmap.us/project/20)| Realign buildings|Active|

#### Workflow:
1. Pick a task from the Tasking Manager.
2. Load the Bing or Mapbox Satellite imagery to JOSM.
3. Install [JOSM Buildings Plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/BuildingsTools) for easy tracing.
4. Inspect the imagery to find the missing buildings.
4. Add only missing buildings.

#### Shortcuts
- `B` to start with buildings tool
- `X` to extrude building shapes as per the imagery.
- `Shift+Ctrl` to rotate buildings.
- `Q` to orthogonalize buildings
- `Shift+J` to merge polygons

![buildings](https://cloud.githubusercontent.com/assets/3423533/11465288/843a25ae-975d-11e5-9501-b79ba3d6356d.gif)

#### Filters
Add a inverse filter `building=yes` to highlight only buildings in the downloaded area.
![buildingfilter](https://cloud.githubusercontent.com/assets/3423533/11465462/d03ec792-975e-11e5-8215-3e4cb645739a.gif)

**Changeset Comment**: `Added buildings https://github.com/mapbox/mapping/issues/141 `
**Source**: Bing/Mapbox

**Comment by ramyaragupathy** [comment]
At present we are doing a trial run of a few blocks in the task, to arrive at a figure for number of buildings added by one person in an hour.

**Comment by srividyacb** [comment]
We compared the building coverage using publicy available data in [Palo Alto](https://www.google.com/fusiontables/DataSource?docid=1r-wrSG94TjWWCJVB79B6F_BkYK1-ar0SCyq0AkQM#rows:id=1). Based on this analysis and visual check with Bing imagery, only a few buildings and building details are missing in OpenStreetMap.

Using Palo Alto public data building as baseline, we ran the analysis for building coverage estimates. 

#### How did we do this?

- We converted the Palo Alto building polygons to points/centroids to improve the speed in processing.
- We ran a point-in-polyogn analysis in QGIS to count the number of buildings within each block of the TM.
- Most of Palo Alto lies within 14 TM blocks. The table of raw counts below:
 
Block | Building Count
----|----|
1 |818
2|1283
3|1367
4|1313
5|809
6|1158
7|1204
8|1263
9|1136
10|1095
11|1118
12|1038
13|922
14|784

#### Findings
- Building count range is from 784 to 1367 for each block. The average is **1,093** per block. 
- For [164 blocks](https://gist.github.com/srividyacb/c6be0dc3524b65196b26) we initially identified as less building coverage area, an estimate of ~1,79,000 buildings should be added to SF peninsula. 

#### Trial Run
- [x] Set up the task in OSM-US tasking Manager.  
- [x] @srividyacb @ramyaragupathy to run a trial trace  to calculate the time needed to add buildings per block. 
- [ ] Calculate how much time it take for a **10 members team** to finish the building improvement.

**Comment by ramyaragupathy** [comment]
> to run a trial trace to calculate the time needed to add buildings per block. 

After loading the 164 blocks onto [Tasking Manager](http://tasks.openstreetmap.us/project/12), it was split into 667 blocks.

We ran a trial trace picking blocks where there were no buildings. Here are the number of buildings added in this trial run. 

![screenshot 2015-11-30 15 42 31](https://cloud.githubusercontent.com/assets/3423533/11469059/e0cfcf96-9779-11e5-887e-107d559f5027.png)

Looking at the numbers above, an average of **120 buildings can be added per person per hour.**

> Calculate how much time it take for a 10 members team to finish the building improvement.

As per our [open dataset building analysis](https://github.com/mapbox/mapping/issues/141#issuecomment-160596321), we need to add ~1,79,000 buildings in SF peninsula. Considering 10 member data team working in it, here are the time estimates:

**Per person : 120 buildings per hour**

Buildings to be added| Total buildings per person | Number of people working | Number of hours | Number of buildings per day | Estimated number of days to finish task
---|---|---|---|---|---
~1,79,000 | 120 | 10 | 8 | ~9600 | 18

**Comment by srividyacb** [comment]
We have been investigating on the availability of open building datasets for SF peninsula. Here is an overview of the usage terms.

City | Dataset Portal | Dataset Availability | License
------------ | ------------- | ------------- | -------------
Palo Alto | [KML](https://www.google.com/fusiontables/DataSource?docid=1r-wrSG94TjWWCJVB79B6F_BkYK1-ar0SCyq0AkQM#rows:id=1) | OSM coverage is good | 
Redwood City | http://webgis.redwoodcity.org/community/ | Yes and already imported | 
San Mateo | https://data.smcgov.org/browse | No 
Sunnyvale | [CommunityDevelopmentDivisions](http://sunnyvale.ca.gov/Departments/CommunityDevelopment/CommunityDevelopmentDivisions/Building.aspx) | No 
San Bruno | No portal 
Millbrae | No portal
Daly City | No portal
Menlo Park | https://data.menlopark.org/browse?q=building | No

cc @ramyaragupathy @maning @planemad

**Comment by planemad** [comment]
**Progress**
<img width="364" alt="screenshot 2015-12-15 01 41 09" src="https://cloud.githubusercontent.com/assets/126868/11792625/0b875fe8-a2cd-11e5-87ef-863f81d5c99f.png">
- [5967 buildings](http://overpass-turbo.eu/s/dgj) added in the last 24 hours by team of 12.

**Comment by ramyaragupathy** [comment]
Knocked off those blocks those were already covered in #135 and #136. This marks 35% of the task complete! 
![screenshot 2015-12-15 12 10 08](https://cloud.githubusercontent.com/assets/12103383/11803855/d51e4248-a324-11e5-8780-abe0fd186b13.png)

**Comment by pratikyadav** [comment]
Use this `building` layer to ensure that all buildings are covered in the blocks without downloading the data.
`tms[99]:https://api.mapbox.com/v4/pratikyadav.332dd523/{zoom}/{x}/{y}.png?access_token=pk.eyJ1IjoicHJhdGlreWFkYXYiLCJhIjoiMTA2YWUxNjRkNmFmZGQ4YzAxZWFiNDk0NDM1YjE1YjAifQ.4P6N5dNmA_WQXd3BsJvu5w`

This will make sure that we are not missing buildings at the corners of the task boundary.

![screen shot 2015-12-18 at 12 51 10 am](https://cloud.githubusercontent.com/assets/12744420/11879477/8be325e0-a521-11e5-8c38-32539ed94acd.png)

**Comment by jothirnadh** [comment]
![screen shot 2015-12-21 at 2 00 43 pm](https://cloud.githubusercontent.com/assets/8401827/11926472/4cdb3a5a-a7eb-11e5-9926-4b480bb5ead3.png)

The houses in the [above image](http://tasks.openstreetmap.us/project/12#task/131) are transportable or temporary ones, so we are not tracing such kind of buildings/houses.

**Comment by ramyaragupathy** [comment]
Now that the tracing and validation is complete for [#12](http://tasks.openstreetmap.us/project/12), we are focusing on project [#14](http://tasks.openstreetmap.us/project/14).

**Comment by karitotp** [comment]
In the task I was working I found this Apple Campus  that does not match Bing satellite.
What to do in this case?

![screenshot from 2016-01-07 16 35 42](https://cloud.githubusercontent.com/assets/11504548/12183420/bb70c330-b55c-11e5-95bf-5284d18e1b5d.png)

**Comment by talllguy** [comment]
@karitotp Cool! I believe you've found the Spaceship campus!
![apple_campus_2_rendering](https://cloud.githubusercontent.com/assets/1827881/12187291/a689c766-b578-11e5-9e7f-a52b992129e6.jpg)

It is under construction, so you may want to trace a `landuse=construction` around the whole area.

[More Info](https://en.wikipedia.org/wiki/Apple_Campus#Apple_Campus_2)

**Comment by abhisheksaikia** [comment]
We are focusing now on project [#15](http://tasks.openstreetmap.us/project/15) in SF building tracing as the [Beverly Hills Task](http://tasks.openstreetmap.us/project/16) is now on hold.

**Comment by RichRico** [comment]
I found some imported buildings that not match with Bing or Mapbox satellite imagery. Here are the picture and the changeset.

https://www.openstreetmap.org/way/377379461/history
![img](https://cloud.githubusercontent.com/assets/8484029/12361783/15ecff7c-bb8e-11e5-88d3-2349d982ba40.png)

**Comment by Rub21** [comment]
@planemad @maning @srividyacb : How is @mapbox/india-office  working in places where the buildings are offset? . Which decision are you taking?, we found some places where the buildings are offset and they are created in 2011, 2012  some of them are recently editions.  We are consider realign those buildings, however we need  to be agree  all the data, What  do you think?

**Comment by Andygol** [comment]
p/chat with @Rub21 

in the same area I faced with buildings without offset and buildings that were shifted - so I decide realign all shifted buildings
 some time shape of imported building is mismatched to the real building on the imagery
/cc @mapbox/india-office

**Comment by ediyes** [comment]
Here https://www.openstreetmap.org/way/240425868/history#map=19/37.47142/-122.25689  I found many buildings are offset that were created two years ago.
![image](https://cloud.githubusercontent.com/assets/5991158/12402372/8b7cb0fc-bdfa-11e5-8b16-bf2a23500e29.png)
What to do? 

cc. @Rub21 @Andygol

**Comment by Andygol** [comment]
@ediyes 
I realigned buildings in such case

**Comment by abhisheksaikia** [comment]
In relation to the comment by @ediyes above, I have noticed significant amount of imports in the Palo Alto area by one certain user: [oldtopos](https://www.openstreetmap.org/user/oldtopos). The link to a changeset containing mass imports in buildings in the area: https://www.openstreetmap.org/changeset/17095207. In most cases there is an offset of the buildings with the Bing imagery as pointed by @ediyes , but in some cases there is also the problem of buildings having different footprints compared to Bing imagery and also buildings not being present in the Bing imagery.

![screen shot 2016-01-19 at 4 17 38 pm](https://cloud.githubusercontent.com/assets/13744156/12416566/33a8d012-bec8-11e5-86ca-3b8632dfa211.png)

*The footprints of buildings with addresses which are not present in Bing Imagery*

![screen shot 2016-01-19 at 4 19 47 pm](https://cloud.githubusercontent.com/assets/13744156/12416622/7abd531a-bec8-11e5-94bd-c24fabf49bca.png)

*Buildings with significant offset with the Bing imagery and also buildings with footprints that differ quite radically from the Bing imagery*

### Next actions:

* Should these buildings be aligned and corrected according to the satellite imagery or should they be left untouched?
* Possibly contact the user: [oldtopos](https://www.openstreetmap.org/user/oldtopos) asking him to look into his edits?

CC: @ramyaragupathy @maning @pratikyadav @Rub21

**Comment by abhisheksaikia** [comment]
An invalid coastline boundary is also observed inside residential areas in Palo Alto area. The changeset comment for the incorrect coastline is: https://www.openstreetmap.org/changeset/11034409.

![screen shot 2016-01-19 at 4 31 41 pm](https://cloud.githubusercontent.com/assets/13744156/12416898/398d38a4-beca-11e5-9c54-a44d33cf2420.png)
*Incorrect coastline inside residential area in Palo Alto*

CC: @maning

**Comment by planemad** [comment]
@abhisheksaikia 
- Comment on the user's changeset to find the source date of the building footprint data. It will help establish wether the imagery or data is outdated
- Comment the the user's changeset with incorrect coastline to ask if any help is needed with the cleanup

Lets give a day for the users to respond, failing which lets have a diary post highlighting the issues and that we will proceed with the cleanup if there is no conflicting opinions. In the meantime, lets skip these areas for now.

cc @mapbox/team-data .

**Comment by abhisheksaikia** [comment]
@planemad The following actions have been taken on the issues: 

> Comment on the user's changeset to find the source date of the building footprint data. It will help establish wether the imagery or data is outdated. 
 
Commented on the user's changeset: http://www.openstreetmap.org/changeset/17095207. Until there is a reply let us hold off on realigning buildings in the Palo Alto area.

> Comment the the user's changeset with incorrect coastline to ask if any help is needed with the cleanup

@maning is looking into the issue and the possibility of reverting the changeset.

cc @mapbox/team-data

**Comment by maning** [comment]
>  incorrect coastline is: https://www.openstreetmap.org/changeset/11034409.

I investigated this data today. It looks like the `landuse=residential`, `place=neighborhood` was **orthogonalized by mistake**!

![screen shot 2016-01-19 at 17 13 08](https://cloud.githubusercontent.com/assets/353700/12418035/85d9bbb2-bed2-11e5-9a9d-cfe3a3e98b2c.png)

Based on the changeset info, the last editor was [Sarr_Cat](https://www.openstreetmap.org/user/Sarr_Cat), but that is not the full story.  The OSM changeset view  does not tell you who was the last editor of the existing nodes. I used the [augmented diff visualizer](http://overpass-api.de/achavi/) to check this area.

The visualizer clearly shows changes in a given view.  In this case, it was confirmed that the polys was edited by Sarr_Cat.

![screen shot 2016-01-19 at 17 35 45](https://cloud.githubusercontent.com/assets/353700/12418141/3baf5028-bed3-11e5-8663-d428955456ff.png)

But, if you select a specific node, you see another user.

![screen shot 2016-01-19 at 17 19 04](https://cloud.githubusercontent.com/assets/353700/12418159/5e6ae442-bed3-11e5-90e6-a1c3417186f6.png)

Investigating further, you see that this user moved the node by a few hundred meters.  If you can read lons/lats, you will notice this.  See 3rd and 4th decimal places.

![screen shot 2016-01-19 at 17 25 59](https://cloud.githubusercontent.com/assets/353700/12418185/aaf98110-bed3-11e5-91ca-038faec9a447.png)

Now we know who the actual editor and changeset who messed this up: https://www.openstreetmap.org/changeset/36659139

Unfortunately a full revert is not possible because the editor did a lot edits: **420 - created, 1380 - modified and 157 - deleted**.  Some are good ones.  I did a partial revert by selecting only the nodes affected.  All [good now](https://www.openstreetmap.org/way/155870761/history).  

![screen shot 2016-01-19 at 17 13 34](https://cloud.githubusercontent.com/assets/353700/12418315/986ca9f4-bed4-11e5-8c8f-966784869bfa.png)

*Faith in humanity restored.*

**Takeaways**

* **Do not blindly square any feature within your task**.  There are ways to avoid this.  
 * Run JOSM filters to avoid touching other data.  
 * If you have to "square" many features, select only those you modified.  In JOSM, click *Selection* and type `type:way modified` or `building modified` .
 * Always review your edits before upload, run the JOSM validator, review what features you modified before hitting the  **Upload changes** button.

![screen shot 2016-01-19 at 17 51 26](https://cloud.githubusercontent.com/assets/353700/12418440/5b1b9c80-bed5-11e5-9c1a-72e174467065.png)

* We need **better tools to get a better picture of what was changed (created, modified and deleted)**.  Augmented diff visualizer gives us this view.  Fortunately, we have such a tool under testing.  See: http://ec2-52-90-240-32.compute-1.amazonaws.com/

cc/ @abhisheksaikia @planemad  @Rub21 @dannykath

**Comment by planemad** [comment]
Nice sleuthing @maning :mag: 

Wonder if we could catch this with osmlint? @Rub21

**Comment by abhisheksaikia** [comment]
In case of invalidated blocks in the [SF task-3](http://tasks.openstreetmap.us/project/15), it has been observed that a lot of invalidation was due to alignment issues. As of now, [we are not re aligning the buildings](https://github.com/mapbox/mapping/issues/141#issuecomment-172821032). So, if there are missing buildings in a invalidated block and other issues those can  be corrected please go ahead doing it. But no re-alignment should be carried out until further update on this.

cc @mapbox/team-data

**Comment by talllguy** [comment]
I have seen other questionable edits by that Sarr_Cat user. Noted.

**Comment by abhisheksaikia** [comment]
#### SF building tracing Summary

**Objective:** Add missing building footprints in SF Peninsula

**Prior Tasks:** https://github.com/mapbox/mapping/issues/135, https://github.com/mapbox/mapping/issues/136

<img width="337" alt="screenshot 2015-11-23 11 49 18" src="https://cloud.githubusercontent.com/assets/126868/11330842/3f4c772e-91d8-11e5-8da2-bd11f0277ac7.png">

**Focus Area**: [1290 sq.km](https://gist.github.com/732acea19b0336e418d0)

**Estimates**: [~1,79,000 buildings](https://github.com/mapbox/mapping/issues/141#issuecomment-160596321)

**Duration**: **[63 days](https://github.com/mapbox/mapping/issues/141#issuecomment-160604840)[17/11/2015-18/01/2016]**

**Buildings Added**: [173447 buildings](https://github.com/mapbox/mapping/issues/141#issuecomment-164547016)

**Team:** @mapbox/india-office and @mapbox/peru-office 

#### Subtasks

Tasks | Description|Start|End(ETA)|Validation
---|---|---|---|---|
[Mountain View](http://tasks.openstreetmap.us/project/9) | [Adding buildings](https://github.com/mapbox/mapping/issues/136) |11/17 | 11/24|[Completed](https://github.com/mapbox/mapping/issues/136#issuecomment-162846008)
[Menlo Park](http://tasks.openstreetmap.us/project/11) | [Adding buildings](https://github.com/mapbox/mapping/issues/135) |11/25 |12/03 |[Completed](https://github.com/mapbox/mapping/issues/135#issuecomment-161922079)
[Missing Buildings](http://tasks.openstreetmap.us/project/12) | [Adding buildings](https://github.com/mapbox/mapping/issues/136) |12/04 |12/28 |Completed
[Missing Buildings in SF Peninsula](http://tasks.openstreetmap.us/project/14)|[Adding buildings](https://github.com/mapbox/mapping/issues/136)|01/04|01/06|Completed|
[Filling gaps in SF Bay](http://tasks.openstreetmap.us/project/15)|[Adding buildings](https://github.com/mapbox/mapping/issues/136)|01/08|01/18|Completed|

**Missing buildings added**

Mapper | SF Task-1 | SF Task-2  | SF Task-3 | Total buildings per person
--- | --- | --- | --- | ---
aarthy | 0 | 384 | 0 | 384
abel801 | 10070 | 0 | 0 | 10070
andygol | 2661 | 1421 | 15 | 4097
calfarome | 8041 | 4259 | 3814 | 16114
Chetan_Gowda | 1365 | 2035 | 559 | 3959
dannykath | 1661 | 2701 | 2698 | 7060
ediyes | 18340 | 0 | 5047 | 23387
jinalfoflia | 1601 | 723 | 0 | 2324
Jothirnadh | 4450 | 622 | 199 | 5271
karitotp | 3152 | 2770 | 2634 | 8556
Luis36995 | 13610 | 2936 | 4336 | 20882
lxbarth | 383 | 0 | 0 | 383
manings | 3944 | 0 | 1 | 3945
mikelmaron | 2 | 0 | 0 | 2
nikhilprabhakar | 7913 | 1268 | 1041 | 10222
oini | 2317 | 0 | 72 | 2389
PlaneMad | 1292 | 0 | 0 | 1292
pratikyadav | 2382 | 515 | 155 | 3052
ramyaragupathy | 2573 | 1283 | 160 | 4016
RichRico | 5713 | 5856 | 6537 | 18106
Rub21 | 565 | 0 | 0 | 565
ruthmaben | 1502 | 457 | 898 | 2857
saikabhi | 4676 | 1493 | 407 | 6576
samely | 4734 | 3435 | 7129 | 15298
srividya_c | 1943 | 632 | 65 | 2640
Total | 104890 | 32790 | 35767 | 173447

**Observations:**

* Imagery is outdated in some cases, where new buildings have cropped up. In some of these cases, the new buildings were deleted and the building footprint was traced according to the prevailing satellite imagery. One must careful while coming across such cases. One such instance was [the new Apple spaceship campus](https://github.com/mapbox/mapping/issues/141#issuecomment-169813621) in OSM which was absent from Bing imagery.

* [Large scale imports](https://github.com/mapbox/mapping/issues/141#issuecomment-172816757) were present in some areas in SF. While coming across such cases, it is advisable to leave those areas untouched and start aligning them in a separate cleanup task.


**What more needs to be done:**

* A separate cleanup task needs to be prepared for the SF area to align all the buildings which were part of some previous imports.
* Publish comms on the task in the form of a blog and diary post.

**Next actions:**

* [ ] @ramyaragupathy to publish a blog and a diary post on the task completion.

* [x] Add the project to [completed projects](https://github.com/mapbox/mapping/wiki#completed) in [mapping wiki](https://github.com/mapbox/mapping/wiki) and update the final statistics of the project.

* [ ] @ramyaragupathy and me to put up a cleaup task by the end of the week.

**Comment by planemad** [comment]
@mapbox/team-data based on reports of misaligned imported buildings https://github.com/mapbox/mapping/issues/141#issuecomment-172050189 we have a cleanup task to focus on these areas with misaligned footprints.

**Task** http://tasks.openstreetmap.us/project/20

**Important**
- The cleanup areas cover the Apple campus at Cupertino and other locations which may have new developments not in the imagery https://github.com/mapbox/mapping/issues/141#issuecomment-169813621 
- Only cleanup footprints that have not been edited in the last two years. Relevant JOSM filters are included in the task instructions.

**Comment by chtnha** [comment]
When proceeding with the cleanup task: http://tasks.openstreetmap.us/project/20 , this filter must be applied: `timestamp:2005-12-31/2014-12-31 building` .This filter must be added to hide the recently added buildings (from 2015 onwards) as these buildings might be added by local mappers from the ground even though they are absent in satellite imagery e.g. [Apple Spaceship Campus](https://github.com/mapbox/mapping/issues/141#issuecomment-169813621) and we dont delete any recent building inadvertently.

![building_filter](https://cloud.githubusercontent.com/assets/6770741/12781440/6646eb34-ca9a-11e5-92a8-2355926ebc09.gif)

**Comment by lxbarth** [comment]
> @mapbox/team-data based on reports of misaligned imported buildings #141 (comment) we have a cleanup task to focus on these areas with misaligned footprints.

@planemad - can we break this work into a separate ticket and close here? The misaligned footprints aren't due to any mapping efforts led up on this ticket here.

**Comment by abhisheksaikia** [comment]
>@planemad - can we break this work into a separate ticket and close here? The misaligned footprints aren't due to any mapping efforts led up on this ticket here.

@lxbarth  Separate ticket for the cleanup task is created: https://github.com/mapbox/mapping/issues/152. This ticket will be closed after the comms are up and validation for [SF task-3](http://tasks.openstreetmap.us/project/15#) is complete. 

cc @mapbox/team-data

**Comment by ramyaragupathy** [comment]
Comms are up and the validation is :100: done.
