### ISSUE TITLE
Mapping turn lanes in SF peninsula, DC and LA

### ISSUE THREAD

**Issue by abhisheksaikia** [mapbox/mapping#153]
**Objective:** Map missing [turn lanes](http://wiki.openstreetmap.org/wiki/Key:turn:lanes) from tertiary and up in SF peninsula, DC and LA.

**Team:** @mapbox/team-data

**Features to map**: Turn lanes (motorway, trunk, primary, secondary and tertiary) from satellite imagery

**Focus Area**: SF peninsula and DC

**Estimated features to map**: *unknown*

**Mapping speed**: *unknown*

### Available data sources
Source | Description|Quality|License 
---|---|---|---|
Mapbox Satellite | Imagery | High |:white_check_mark: 
Bing Imagery | Imagery | High | :white_check_mark: 

### Tasks
Location | Description|Start|End(ETA)|Validation
---|---|---|---|---|
[Palo Alto - Redwood City](http://tasks.teachosm.org/project/119) | Trial run for estimates and workflow evaluation|12/10 |(12/11) | Completed
[SF Peninsula](http://tasks.openstreetmap.us/project/17) | Turn lanes on motorway and trunk junctions in San Francisco Peninsula | 20/01/16 | 5/02/2016 | Completed
[Turn lanes in Palo Alto - 1](https://github.com/mapbox/mapping/issues/144) | Mapping turn lanes on highways tertiary and up in Palo Alto | 08/02/16 | 09/02/16 | Completed |
[Turn lanes in DC - 1](http://tasks.openstreetmap.us/project/19) | Mapping turn lanes on highways tertiary and up in DC | 08/02/16 | 08/02/16 | Completed |
[Turn lanes in SF city](http://tasks.openstreetmap.us/project/21) | Mapping turn lanes on highways tertiary and up in SF city |09/02/16 | 10/02/16 | Completed |
[Turn lanes in DC](http://tasks.openstreetmap.us/project/22) | Mapping turn lanes on highways tertiary and up in DC | 11/02/16 | 12/02/16 | Completed |
[Turn lanes in LA](http://tasks.openstreetmap.us/project/23) | Mapping turn lanes on highways tertiary and up in LA | 12/02/16 | 29/03/2016 | Completed |
[Turn lanes in SF peninsula upto San Jose ](http://tasks.openstreetmap.us/project/24) | Mapping turn lanes on highways tertiary and up in SF peninsula |  |  |  |
#### Setup
- **[Task Config](https://gist.githubusercontent.com/planemad/9c693d5c9addd07148c4/raw/b565d53e2ee1b4ba48752b4c7a4b5b07594589cb/josm-config-turnlanes.json)**
- Activate the following in from JOSM preferences > Map Settings
 - **Map Paint Styles**: Lanes and road attributes
 - **Tagging Presets**: lane attributes
- Filter out non road features with `boundary: | leisure: | landuse: | waterway: | amenity: | natural: | building:`
- Add inverse filter: `highway=motorway | motorway_link | trunk| trunk_link | primary | secondary | tertiary`
- Read http://wiki.openstreetmap.org/wiki/Key:turn:lanes

#### Mapping
- Check all motorways for turn lanes at exits and entry points
![](https://cloud.githubusercontent.com/assets/126868/11710074/b58b52e4-9f42-11e5-971a-000a699a0b6d.png)
- Split the road into segments based on the total number of lanes for the segment
- For each road segment tag the turn lanes based on the road markings in the direction of the way. Eg. `turn:lanes=left|through|right`. See [OSM turn:lanes](http://wiki.openstreetmap.org/wiki/Key:turn:lanes)
- For bi-directional segments, use `turn:lanes:backward=` and `turn:lanes:forward=` to specify turn lanes in each direction.
- Verify correct tagging using the `Lane attributes` style
![](https://cloud.githubusercontent.com/assets/126868/11713668/d3f6d498-9f5a-11e5-91ea-5d9ab5714b39.png)

#### Issues to keep in mind:

* For now we [ignore adding cycle lane marking](https://github.com/mapbox/mapping/issues/144#issuecomment-174608112)
* `slight_left` and `slight_right` can be ignored and instead `right` and `left` turn lane tags should be used to [avoid ambiguity](https://github.com/mapbox/mapping/issues/144#issuecomment-175074272).
* Bi-directional lanes such as [these](https://github.com/mapbox/mapping/issues/144#issuecomment-176185349) is also optionally ignored during turn lane mapping.

**Changeset Comment**: `Add missing turn lanes from satellite imagery https://github.com/mapbox/mapping/issues/153`

**Source**: Bing/Mapbox

**Comment by jinalfoflia** [comment]
The imagery at some places is not very clear and at-times the turn-lanes are covered by cars. In situations like these `Mapillary plugin` can be used. If there is Mapillary imagery coverage in that area, they can used to verify the presence of turn-lanes.

**Name of the plugin:** Mapillary

![turnlanes_mapillary](https://cloud.githubusercontent.com/assets/4470913/12884912/6b405d1e-ce87-11e5-8d0f-cd8a8a8b3dfd.gif)

Additionally, `Strava global-heat cycle` layer can used to verify if a particular lane is a cycle-way.
`tms[16]:http://globalheat.strava.com/tiles/cycling/color3/{zoom}/{x}/{y}.png`

/cc @mapbox/team-data

**Comment by jothirnadh** [comment]
The new [Turn lane mapping task of SF city](http://tasks.openstreetmap.us/project/21) is up for mapping. This task will include all the turn lanes from tertiary and above. If you face problems in loading the blocks please split it.

cc @mapbox/team-data

**Comment by Rub21** [comment]
@mapbox/peru-office  is jumping on this task!, 

Guys tengan en consideracion las intruciones.. :)

**Comment by jothirnadh** [comment]
The turn lane mapping tasks, [DC task - 1](http://tasks.openstreetmap.us/project/19) and [Palo Alto task - 1](http://tasks.openstreetmap.us/project/18) are completed and validated as well. The [new DC turn lane mpping task](http://tasks.openstreetmap.us/project/22) is also up for mapping.

cc @mapbox/team-data

**Comment by jothirnadh** [comment]
## Statistics of Turn lane mapping done in SF Peninsula

**Duration:** Jan 20th  to Feb 10th

**Team:** @mapbox/team-data 
![screen shot 2016-02-11 at 4 02 05 pm](https://cloud.githubusercontent.com/assets/8401827/12974293/db9b7640-d0d8-11e5-8f53-622c8ea15e34.png)


Roads marked with turn lanes | Total
--- | ---
motorway | 70
motorway_link | 2111
trunk | 432
trunk_link | 116
primary | 1317
secondary | 1569
tertiary | 518
**Total** | **6133**

cc @lxbarth and @mikelmaron

**Comment by ruthmaben** [comment]
How do we go forward with tagging these @mapbox/team-data 

![screenshot 2016-02-11 15 53 30](https://cloud.githubusercontent.com/assets/10308123/12974483/5d952b2c-d0da-11e5-834c-808f70d55b48.png)

**Comment by planemad** [comment]
^ Not completely sure whats going on here. Would this be `left|left;through` @Andygol ?

**Comment by abhisheksaikia** [comment]
^I think this might be : `left | merge_to_left;through` @planemad @Andygol ?

**Comment by Andygol** [comment]
@ruthmaben 
>Would this be **left|left;through**

this is right tagging :point_up:

**Comment by Andygol** [comment]
@planemad  
could you change `changeset comment` or create new [task config](https://gist.githubusercontent.com/planemad/9c693d5c9addd07148c4/raw/02f52e972de61822096e6ce77de688ed23589c3e/josm-config-turnlanes.json) for http://tasks.openstreetmap.us/project/22 ?

**Comment by Andygol** [comment]
Please pay attention in a case `lanes=3` or similar. There is could be specified number of lanes in `:forward` and `:backward` directions

<img width="685" alt="java openstreetmap editor 2016-02-11 14-32-50" src="https://cloud.githubusercontent.com/assets/369696/12976582/de602318-d0cd-11e5-85bd-5d90088ead71.png">

**Comment by talllguy** [comment]
## DC 3 inch imagery

@abhisheksaikia DC GIS has an open data site with some additional resources, including **3 inch imagery from 2015**, which was just posted four weeks ago. If we could somehow get this in JOSM, it'd be very useful. It is redacted around a few sensitive areas, e.g. The White House, but it is otherwise complete

* [Searching for "orthophoto" on their open data site](http://opendata.dc.gov/datasets?q=orthophoto&sort_by=relevance)
* [Dropbox link to the 2015 data](https://www.dropbox.com/s/6nozfw8strms7rv/Ortho2015.zip?dl=0)

## Redacted Areas
![2016-02-11 09_14_11-redactedareas pdf - adobe acrobat reader dc](https://cloud.githubusercontent.com/assets/1827881/12978595/db1279aa-d09f-11e5-9440-b9979853747b.png)

**Comment by ediyes** [comment]
Hey @Andygol 
What is the tag for this case?
![image](https://cloud.githubusercontent.com/assets/5991158/12990999/3c02e638-d0db-11e5-9db7-c536e09bca14.png)

cc.  @mapbox/team-data

**Comment by talllguy** [comment]
@mapbox/team-data you guys crushed through this task, wow. Just looking through the data and some of the ones in the *done* areas still do not have turn lanes. What is the protocol to ignore?

http://www.openstreetmap.org/way/379685261/history

**Comment by Andygol** [comment]
@ediyes 
>What is the tag for this case?

`turn:lanes=left|left;through|through`

**Comment by talllguy** [comment]
@Andygol are the turn lane tags supposed to follow the paint on the road, or the intent of the paint? In other words, for routing purposes, would a `turn:lanes=left|foo|foo` tag indicate that at the end of that *segment*, the vehicle must turn left, **or** that the road marking underneath that segment indicates that there is a left turn lane *ahead*?

The reason I ask is while reviewing some of this tagging in DC I've found an instance with a `left` turn lane ends at a one-way (part of a dualized highway) that would be impossible. Though the paint indicates there is a left only restriction, the left only is beyond that intersection at the other part of the one-way pair. I thought it should be `through` until beyond the one-way pair, and then `left` after that.

**Comment by jothirnadh** [comment]
## Statistics of Turn lane mapping done in DC

**Duration:** 1 day

**Team:** @mapbox/team-data 
![screen shot 2016-02-12 at 12 16 26 pm](https://cloud.githubusercontent.com/assets/8401827/13000637/7c0fb3f8-d182-11e5-9ef5-a0185d7cbc43.png)

Roads marked with turn lanes | Total
--- | ---
motorway | 20
motorway_link | 8
trunk | 34
trunk_link | 3
primary | 211
secondary | 59
tertiary | 35
**Total** | **370**

**Observations:**
* The imagery in not clear compared to SF which made it hard to identify turn lanes.
* The number of marked turn lanes in DC are much lesser (370) than the SF region (6133)

**Next actions:**
* Creating a new Turn Lane mapping task in LA region

cc @planemad @lxbarth and @mikelmaron

**Comment by abhisheksaikia** [comment]
> The reason I ask is while reviewing some of this tagging in DC I've found an instance with a `left` turn lane ends at a one-way (part of a dualized highway) that would be impossible. 

@talllguy Regarding your query above^^, can you provide a link to the instance in OSM which will help in better understanding the scenario better? Thanks.

**Comment by Andygol** [comment]
@talllguy 
> would a turn:lanes=left|foo|foo tag indicate that at the end of that segment, the vehicle must turn left 

`turn:lanes=left||` tagging indicates that from the leftmost lane we are allowed to move only in left direction when we reach an intersection/junction.

>or that the road marking underneath that segment indicates that there is a left turn lane ahead?

if we have to prepare to change lane for a left turn from an extra lane we use turn:lanes=slight_left| beforehand of it

http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications

**Comment by abhisheksaikia** [comment]
New tasks for 1) LA : http://tasks.openstreetmap.us/project/23 and 2) Larger SF peninsula: http://tasks.openstreetmap.us/project/24 are up.

cc @mapbox/team-data

**Comment by jothirnadh** [comment]
> Just looking through the data and some of the ones in the done areas still do not have turn lanes. What is the protocol to ignore?

Thanks for flagging this out @talllguy , we are trying our best to identify all the turn lanes marked on Tertiary roads and above, but by mistake we might be missing some due to the poor imagery quality. If you find any of the missing turn lanes, please flag them here so that we can add them.

**Comment by talllguy** [comment]
@Andygol I should have included a screenshot. Here:

![2016-02-12 10_45_55-java openstreetmap editor](https://cloud.githubusercontent.com/assets/1827881/13011721/2734c8ca-d176-11e5-9e58-99970bb494c5.png)
[segment link](https://www.openstreetmap.org/way/131520206)

So here I would say it should be `through|right` on the tagged segment, and then the segment in the middle would have a lane count of 1, with `left` only (assuming no uturns).

The question is if this is about mapping for routing directly.

**Comment by talllguy** [comment]
@jothirnadh I think I understand. If there isn't an explicitly denoted lane restriction visible on the imagery, you'd not tag it. Right?

**Comment by jothirnadh** [comment]
> If there isn't an explicitly denoted lane restriction visible on the imagery, you'd not tag it. Right?

Yes @talllguy we are not tagging the turn:lanes which are not explicitly visible on the imagery. We are also not changing any of the turn:lanes marked by other contributors as they might have marked them using their local knowledge.

> So here I would say it should be through|right on the tagged segment, and then the segment in the middle would have a lane count of 1, with left only (assuming no u turns). 

What you said is true @talllguy, but thinking it in a mappers perspective it is hard to map these, as the turn directions differ from country to country. In US, a person travels on the right side of the road and coming to India (my native country) or London people stick to left. So it is hard to differentiate these rules. Even OSM wiki is not having much information on where to start and stop the `turn:lane` tagging. 

![screen shot 2016-02-13 at 3 39 00 pm](https://cloud.githubusercontent.com/assets/8401827/13027145/aa6ed8d6-d269-11e5-880f-426e9a09086d.png)

According to my perspective it is important to add the tag `left|right` instead of `through|right` as the user needs to decide the lane beforehand, which he wants to continue his journey and it is what a [routing engine](http://project-osrm.org/) (oce of the example) do. And tagging the next segment with `left|through` tag (not only `left` tag) is a good thing but not a necessary one as the other lanes are already marked with directions which will just be a redundant information added to any of the routing engine. Please let me know if I'm wrong or missing some information.

**Comment by jothirnadh** [comment]
I recently got a message from a OSM mapper saying that 

> A while back, I noticed that some service roads I added under Building 20 were [moved by your colleague](https://www.openstreetmap.org/changeset/35939027) according to outdated satellite imagery. He seemed okay with me reverting these changes. I checked again today, and the service roads were moved again.
I reverted the part of the changeset. Could you follow up with your team and make sure nobody else tries to move these service roads?

@mapbox/team-data It seems that the imagery is outdated in some regions. Don't try to align the roads while trying to add turn lanes. Check for the presence of GPS traces before aligning the roads to satellite imagery. You can also use the 'recent edits' tool to highlight all the edits that are made in that region within one year to avoid further problems. 
![recent edits](https://cloud.githubusercontent.com/assets/8401827/13046472/0123df50-d3ff-11e5-9723-b87511b0e93d.gif)

In the above GIF the features highlighted in green are recently modified once and the rest are from older changesets. Using this tool we can identify the recently changed edits and avoid aligning them.

cc: @planemad and @Andygol

**Comment by nikhilprabhakar** [comment]
While working on the [LA turn lanes task](http://tasks.openstreetmap.us/project/23#task/133), I came across a place where one single stretch with `through|through` symbols on the road. Can someone help me identify whether the below are actually turn lanes?
![screen shot 2016-02-15 at 3 55 03 pm](https://cloud.githubusercontent.com/assets/11845908/13046953/d01ecd18-d401-11e5-8355-d24413a7d79c.png)

This have dotted lines and not solid line like the native turn lanes.

**Comment by jothirnadh** [comment]
## Problems faced while mapping turn lanes in LA
Almost from the mid of January we are working on mapping turn lanes and so far we almost added ~6500 turn lanes in SF and DC. We got a clear understanding on how the turn lanes are marked in these regions, but coming to LA the scenario is a bit different. As per the discussion with the team I am drafting out the issues being faced while mapping turn lanes in LA. 

* **Confusion with parking lanes and turn lanes**
In SF and DC the parking lanes are well demarcated from the actual drive lanes with solid lines, but in LA there is no proper demarcation between drive lanes and parking lanes due to the absence of markers on the road. In this case the only way to determine parking lanes is to look for parked cars in the side lanes which is not a full proof method.

![screen shot 2016-02-17 at 6 08 33 pm](https://cloud.githubusercontent.com/assets/8401827/13109930/7fbb39c2-d5a2-11e5-844b-f8745ca20683.png)

In the above case you can see there are cars parked on the sides of the road but those lanes are not separately demarcated as parking lots.
* **Is it important to map small turn lanes**
In LA we are finding a lot of small turn lanes along the stretch of the road apart from junctions.

![micro mapping-1](https://cloud.githubusercontent.com/assets/8401827/13105750/bdc6c9ba-d58a-11e5-9483-74c267326886.gif)

In the above GIF the road started with a junction and continued with a lot of minor turn lanes along the stretch. Are we supposed to map these turn lanes?

* **Starting and ending of a turn lane**

While validating blocks we came across many scenarios of starting a turn lane in wrong location. You can end a turn lane in a junction, but always start a turn lane where the **exact turn lanes in the imagery starts**.
![screen shot 2016-02-17 at 6 25 09 pm](https://cloud.githubusercontent.com/assets/8401827/13110125/0fe83ad0-d5a4-11e5-82ff-00245d0ba043.png)

cc @shvrm @lxbarth  @maning @planemad @Andygol

**Comment by abhisheksaikia** [comment]
While splitting turn lanes in case of long stretches of roads which are in turn a part of a relation, often times during uploading, there is the error of `Role verification problem`. This is due to the fact that a `relation:route` has defined `role` which it prompts the mapper to add in case a part of the route has been split and tagged with `turn:lanes:=*`. Look into this wiki for more clarity on `relation:route`: http://wiki.openstreetmap.org/wiki/Relation:route. In these cases the errors can be ignored, as in the case below:

![test](https://cloud.githubusercontent.com/assets/13744156/13142437/0d28f6da-d663-11e5-94ad-910bef186293.gif)



**While in this case, the error can be ignored, one must be careful while splitting any route which is part of a relation and check carefully into any possible errors flagged during verification.**

cc @maning

**Comment by maning** [comment]
@Andygol This is a single way with forward and backward turn lanes, but the starting point of the backward lane starts way before the starting point of the forward lane from the intersection to the north.
I can't make it a dual-carriageway because it doesn't have a physical barrier in the middle of the road.

![screen shot 2016-02-23 at 15 22 45](https://cloud.githubusercontent.com/assets/353700/13247992/2aed779e-da42-11e5-8a2a-cac82625a7d7.png)

**Comment by maning** [comment]
Fixing the ^^^ above case, we split the road into 3 ways. Starting from the south we add the following tags:
* way 1: `lanes=7, lanes:backward=4, turn:lanes:backward=left|||`
* way 2: `lanes=7, lanes:backward=4, turn:lanes:backward=left|||, lanes:forward=3, turn:lanes:forward=||right`
* way 3: `lanes=7,lanes:forward=3, turn:lanes:forward=||right`

![screen shot 2016-02-23 at 15 47 58](https://cloud.githubusercontent.com/assets/353700/13248531/d9d5d786-da44-11e5-9a1c-324cfc2b007d.png)

**Comment by Andygol** [comment]
Here is some tips how to add recently used tags. Just hold `Shift` pressed while choosing recently added tags from the `Add value` dialog. You may add recently used tags selecting it by mouse or using shortcut `⌘+⇧+[number]`

![turn_lanes_mapping](https://cloud.githubusercontent.com/assets/369696/13318375/0e80f81a-dbc3-11e5-8de6-cd266444dd7e.gif)

**Comment by planemad** [comment]
Summarizing discussion from https://github.com/mapbox/mapping/issues/155

>
- The project focus is on turn lanes. So for completion we need correct addition of only `turn:lanes`, `turn:lanes:forward`, `turn:lanes:backward`. All other tags are extra information and not considered for project completion or validation.
- Only segments which have a turn lane needs to be tagged :point_up: . No turn lanes = no need for turn lane tag
- Adding `lane=` to help with style visualization and validation is ok, but not requirement for project completion. We can do lane mapping as a separate project for more efficient mapping and easier validation later.

cc @mapbox/team-data

**Comment by jothirnadh** [comment]
As per discussion with @pratikyadav @mikelmaron and @maning  we are updating our workflow to add dual carriageways in case of physical separations on roads. **At present, we have decided to add dual carriageways only for roads which are not part of any relation.**

### Dual-carriage way vs Fwd-Bkwd tagging

At some locations we are finding roads mapped by single carriageway while the imagery shows clear separation between roads.

![screen shot 2016-02-19 at 5 38 02 pm](https://cloud.githubusercontent.com/assets/12744420/13175306/91d0cfda-d72f-11e5-9fd8-5b1b354c061e.png)

**When to add dual carriageway?**
- Add Dual-carriage when 
 - you see physical separation betweens roads
 - **no relation is attached to the way.**
- Add `turn:lanes` tag to both the ways.

This is added as a long term fix so that the present work of mapping `turn:lanes` does not become redundant in case dual carriageways are mapped in the future.

cc @mapbox/team-data

**Comment by Andygol** [comment]
Here I've spotted difference in Bing and Mapbox imagery. Bing imagery was created `1/3/2015-1/17/2015` date of Mapbox imagery unknown. I suggest that Bing is newer 
https://www.openstreetmap.org/#map=18/33.774646/-118.043975
  
![bing_mapbox_img_diff](https://cloud.githubusercontent.com/assets/369696/13406497/7ed1815e-df2c-11e5-895c-70e90f79c8a4.gif)

**Comment by Andygol** [comment]
I've updated alignment of highway :point_up:  according Bing imagery + Mapillary 
https://www.openstreetmap.org/changeset/37530197

**Comment by jothirnadh** [comment]
There are 4206 turn lanes, tagged to highways with no exact demarcation on the roads in LA. According to the https://github.com/mapbox/mapping/issues/144#issuecomment-175635302 we are only supposed to tag a turn lane if there is solid white lines marked on the road.

With reference to @planemad came up with this [workflow](https://gist.github.com/jothirnadh/625394a473e506a82df9) and cleaned up all the wrongly tagged turn lanes.

**Note:** @mapbox/team-data  don't add any turn lanes if there are no solid white markings on the road.

// CC: @planemad @Andygol @maning @Rub21

**Comment by abhisheksaikia** [comment]
ESTIMATED :ship: DATES for [turn lanes mapping task in LA](http://tasks.openstreetmap.us/project/23#) for @mapbox/team-data :

* Progress till now: 67% done.
* Daily Progress: 4-5 %
* Estimated days remaining to complete the mapping task: ~**8 working days**.
* Estimated days required for validation: ~**1 week (5 working days)**
* Estimated time required to :ship: both mapping validation in turn lanes: ~**3 weeks (25th March, 2016)**.

cc @lxbarth @planemad @jothirnadh

**Comment by jothirnadh** [comment]
According to https://github.com/mapbox/mapping/issues/144#issuecomment-175635302 we only add `turn:lanes` if there is a solid white turn markings on the road. We will not add empty turn lanes just for the turn lane visualization in JOSM.

![screen shot 2016-03-10 at 2 41 35 pm](https://cloud.githubusercontent.com/assets/8401827/13664806/4c23587c-e6cf-11e5-806b-fb02e8a0ac0c.png)

This issue is already been [flagged and rectified](https://github.com/mapbox/mapping/issues/153#issuecomment-193132347) but still finding it to be repeated by our @mapbox/team-data .

**Overpass query**: http://overpass-turbo.eu/s/eTL

@Rub21 can you [follow this workflow](https://gist.github.com/jothirnadh/625394a473e506a82df9) and and use the above overpass query to clean this up? It would be great if you can document your findings in this ticket.

**Comment by jothirnadh** [comment]
## Statistics of Turn lane mapping done in LA

**Duration:** Feb 12th to March14th (*still working*)

**Team:** @mapbox/team-data 

Users | tunr:lanes | turn:lanes:forward | turn:lanes:backward | Total
--- | --- | --- | --- | ---
aarthy | 11 | 11 | 10 | 32
andygol | 706 | 434 | 415 | 1555
calfarome | 1259 | 1191 | 1223 | 3673
Chetan_Gowda | 20 | 28 | 29 | 77
dannykath | 2073 | 1006 | 980 | 4059
ediyes | 1301 | 946 | 936 | 3183
jinalfoflia | 21 | 22 | 24 | 67
Jothirnadh | 149 | 2107 | 2014 | 4270
karitotp | 3017 | 3002 | 2895 | 8914
Luis36995 | 1118 | 322 | 306 | 1746
manings | 32 | 21 | 25 | 78
nikhilprabhakar | 92 | 68 | 58 | 218
oini | 3 | 1 | 3 | 7
PlaneMad | 1 | 2 | 3 | 6
pratikyadav | 69 | 10 | 8 | 87
RichRico | 1863 | 2233 | 2233 | 6329
ruthmaben | 0 | 8 | 20 | 28
saikabhi | 104 | 201 | 205 | 510
samely | 2398 | 1164 | 1159 | 4721
srividya_c | 2 |  | 2 | 4
Total | 14239 | 12777 | 12548 | 39564

**Comment by jothirnadh** [comment]
While @mapbox/team-data working on the mapping of turn lanes in LA two new scenarios were identified. They were: 

**Lanes with restricted access**

These are the areas on streets which are restricted for vehicular traffic.

![screen shot 2016-03-15 at 3 36 36 pm](https://cloud.githubusercontent.com/assets/8401827/13776503/84c34002-ead0-11e5-911d-0581fe9173b7.png)

![screen shot 2016-03-14 at 4 46 03 pm](https://cloud.githubusercontent.com/assets/8401827/13776504/84e64138-ead0-11e5-81f0-7918311ec6dc.png)

![screen shot 2016-03-14 at 4 46 29 pm](https://cloud.githubusercontent.com/assets/8401827/13776505/84e71888-ead0-11e5-9135-553c11d99d12.png)

In the above cases the areas with markings on the roads are not considered as a lane

**Reverse direction turn lanes**

These are the lanes specifically categorised to take U-turn or reverse-turn.

![screen shot 2016-03-14 at 2 25 28 pm](https://cloud.githubusercontent.com/assets/8401827/13776502/84944b6c-ead0-11e5-92fa-0bb2951760ef.png)

These were listed in [Turn Lane mapping guide, QA part](https://github.com/mapbox/mapping/wiki/QA-for-turn-lane-data). Keep us posted with new scenarios so that we can add it to the mapping guide.

**Comment by maning** [comment]
There were some roads that has turn lanes but don't have an actual intersection/junction.  This doesn't make sense, if you see such roads make sure you add the road that intersects with them.

![missing_intersections](https://cloud.githubusercontent.com/assets/353700/13806517/1c018ad0-eb82-11e5-8fe6-f8357ed474cf.gif)

**Comment by jothirnadh** [comment]
Nice catch @maning, yes we are adding the roads at the actual junctions if they are missing.

**Comment by jinalfoflia** [comment]
Found this [scenario](https://www.openstreetmap.org/way/399479021/history) where a separate road is traced from the major road. This is **not** required until there is a physical barrier between the roads. This turn lane can be a part of the existing road itself. So this road will have the following tags `turn:lanes=left|||right`.

![screen shot 2016-03-16 at 3 48 37 pm](https://cloud.githubusercontent.com/assets/4470913/13809049/ee2668a8-eb8e-11e5-8a16-82e38b715c6d.png)

**Comment by abhisheksaikia** [comment]
As per voice with @maning and @planemad, we are scaling down the turn lanes mapping task after the [LA task](http://tasks.openstreetmap.us/project/23) is completed. We will not work on the  next [SF peninsula task](http://tasks.openstreetmap.us/project/24) on turn lanes for now.

Next actions:

* [ ] Complete the remaining blocks in [LA turn lanes mapping task](http://tasks.openstreetmap.us/project/23) and validate them.
* [ ] @jothirnadh and me to put up a detailed summary of the stats on the turn lanes added till now.
* [ ] @jothirnadh and me to discuss on next comms on turn lanes: blog and diary posts and discuss a timeline for getting them out.
* [ ] @maning, @jothirnadh and me to cleanup data in the previously completed tasks in [SF](http://tasks.openstreetmap.us/project/21) and [DC](http://tasks.openstreetmap.us/project/22) on Monday.

cc @mapbox/team-data

**Comment by dannykath** [comment]
While I was validating `turn:lanes:*` in  [L A](http://tasks.openstreetmap.us/project/23#task/301)  
I found a highway:
**https://www.openstreetmap.org/way/13320233/history**
that doesn't match with the satellite imagery:

*Bing Imagery*

![p](https://cloud.githubusercontent.com/assets/8483644/14124659/5818884e-f5cc-11e5-9080-c867a1238021.png)

*Mapbox Imagery*
![a](https://cloud.githubusercontent.com/assets/8483644/14124707/a48c09ee-f5cc-11e5-8fd3-c6953225e2a5.png)

Which satellite imagery should I work with?

@mapbox/team-data

**Comment by aaronlidman** [comment]
@dannykath - I grew up in this area, it is changing a lot right now, but the Bing imagery is correct.

![screen shot 2016-03-29 at 6 20 09 pm](https://cloud.githubusercontent.com/assets/58878/14125755/eb75b4be-f5da-11e5-9338-be66a256d06e.png)

Tiger also shows the correct location.

**Comment by dannykath** [comment]
thanks @aaronlidman :+1:

**Comment by jothirnadh** [comment]
Fixed it as per the bing imagery @dannykath https://www.openstreetmap.org/way/13320233/history#map=18/33.71805/-117.73640

**Comment by abhisheksaikia** [comment]
The [LA turn lanes](http://tasks.openstreetmap.us/project/23) has been completely mapped and validated by @mapbox/team-data. :100: :rocket: 

As discussed [above](https://github.com/mapbox/mapping/issues/153#issuecomment-201173279), we are going to scale down  our turn lanes mapping effort and stop working on it for now. 

#### IMMEDIATE NEXT ACTIONS:
> @maning, @jothirnadh and me to cleanup data in the previously completed tasks in SF and DC.

We are working on cleaning up the previous turn lanes data in SF and DC using overpass turbo.
**Estimated time**: 3 days

>  @jothirnadh and me to put up a detailed summary of the stats on the turn lanes added till now.

@jothirnadh and me to put up the stats by *end of this week* by working with @planemad: derive observations from the statistics and wrap up the LA turn lanes mapping effort.

**Comment by oini** [comment]
## Statistics of Turn Lane mapping in LA:

- **Duration:** February 12th to March 29th
- **Total turn lanes added:** 51,385

![screen shot 2016-04-01 at 4 49 03 pm](https://cloud.githubusercontent.com/assets/1933377/14205593/fd799260-f829-11e5-9897-9c9571db1447.png)

## Overall Statistics for Turn Lane mapping tasks:

- Team: **~12**
- Hours per day: **~5**

Task | Area (square kilometers) | Total number of turn lanes | Turn lane density (per square kilometer) | Percentage of total turn lanes added by Team Mapbox | Turn Lanes added by team in 1 hour | Time taken to add 1 turn lane (minutes) | Percentage of turn lanes starting with `left`
---- | ------------------------ | -------------------------- | ---------------------------------------- | --------------------------------------------------- | ---------------------------------- | ----------------------------- | ---------------------------------------------
**SF** | 278.66 | 1,780 | 6.39 | 51.97% | 12.33 | 4.86 | 70.38%
**DC** | 206.78 | 745 | 3.6 | 81.88% | 114 | 0.53 | 67.54%
**LA** | 7,534.92 | 54,161 | 7.19 | 94.87% | 321.15 | 0.19 | 89.71%

## Conclusion:

Thus we can make the following conclusions based on our observations for the mapping tasks in SF, DC and, LA:

- Currently our team can add **~321.15 turn lanes in an hour**
- Average density of turn lanes in an US city is **~5.73 per square kilometer**
- Average area of a task for an US city is **~2673.45 square kilometers**
- Average percentage of turn lanes in an US city that require mapping is **~76.24%**
- With our current speed, it should take the team **~74 days** to add turn lanes in top 10 US cities
- An average of **~75.88%** of all turn lanes begin with `left`. Thus having a plugin that automatically sets the first lane as left and provides other facilities to enhance the speed of mapping even further would be ideal

cc @abhisheksaikia @jothirnadh @planemad

**Comment by jothirnadh** [comment]
Woot, superb work in pulling out the stats @oini. Great team effort @mapbox/team-data :100: .

![screen shot 2016-04-01 at 5 40 09 pm](https://cloud.githubusercontent.com/assets/8401827/14206449/d7b8f65e-f830-11e5-925c-2f6b5869172e.png)

:point_up_2: hourly stats shows how our team increased the speed from :no_good:  to :+1: :rocket: 

### Next actions
- [ ] Review completed tasks once again and close the ticket for now.

cc:/ @abhisheksaikia @planemad @shvrm

**Comment by gundersen** [comment]
> An average of ~75.88% of all turn lanes begin with left. Thus having a plugin that automatically sets the first lane as left and provides other facilities to enhance the speed of mapping even further would be ideal

Fascinating

**Comment by jothirnadh** [comment]
[Diary](https://www.openstreetmap.org/user/Jothirnadh/diary/38452) has been posted and all the comms are up for validation :100:.

Closing the task for now.
