### ISSUE TITLE
Adding destination sign and exit number using Mapillary [trial]

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/mapping#161]
**Objective:** Mapillary images are a good source to verify and add information to OpenStreetMap. Our goal is to use [Mapillary](https://www.mapillary.com) street photos to add destination sign and exit number.

**Team:** @pratikyadav @jinalfoflia

#### Task Workflow [Trial in progress]

**Imagery layer:** 
- `tms[99]:https://api.mapbox.com/v4/pratikyadav.bbc30660/{zoom}/{x}/{y}.png?access_token=pk.eyJ1IjoicHJhdGlreWFkYXYiLCJhIjoiMTA2YWUxNjRkNmFmZGQ4YzAxZWFiNDk0NDM1YjE1YjAifQ.4P6N5dNmA_WQXd3BsJvu5w`
(_For better visualization of motorway-links_)
- `tms:http://d2cd86j8eqns9s.cloudfront.net/tiles/{zoom}/{x}/{y}.png` (_To detect the presence of Mapillary imagery_)

**Tools used:** [Mapillary plugin for JOSM](http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html)

**Map features that can be mapped:**

- There are [2 major tags](https://taginfo.openstreetmap.org/search?q=destination) regarding mapping of Destination sign and exit number on **motorways**-
- `destination=*` refers to the city/town the road will take you to
- `destination:ref=*` refers to the highway name/number you are going to take.
http://wiki.openstreetmap.org/wiki/Key:destination

**Changeset Comment:** `Adding destination sign and exit number data using Mapillary (https://github.com/mapbox/mapping/issues/161)`
**Imagery:** `Bing and Mapillary`

--
##### Other resources

- [Mapillary](http://www.mapillary.com/map)
- [Cross Country roads](http://crosscountryroads.com/index.html)
- [Aaroads](http://www.interstate-guide.com/)
- [Martin's diary on mapping freeway exits](http://www.openstreetmap.org/user/mvexel/diary/36263)

--

/cc @planemad @lxbarth @maning

**Comment by talllguy** [comment]
[An excellent destination sign quality assurance tool: CheckAutopista2](http://k1wiosm.github.io/checkautopista2/?id=1216551&lat=39.4274&lon=-76.7100&z=11)

I found it on @mvexel 's diary.

On :octocat: https://github.com/k1wiosm/checkautopista2

**Comment by talllguy** [comment]
A related resource presented at SOTMUS 15 http://wiki.openstreetmap.org/wiki/Exit_Info

**Comment by pratikyadav** [comment]
@jinalfoflia  and I spend some time on this and here are our observation

- We tried to come up with a [workflow using combination of imagery, mapillary, Wikipedia and others sources](https://gist.github.com/pratikyadav/54cc55d97d29731ca6c0) 
- Would be better to separate this into 2 tasks-
 - **Adding missing Exit Numbers** 
 - **Adding Destination tag**
- Doing exit numbers first will a good learning curve for the team to read Intersection guiding signboards and will be beneficial when we move towards mapping destination tags that require more experience.



#### Next actions-
- [ ] Open a sperate ticket for exit numbers mapping  and destination tags mapping; @jinalfoflia 
- [ ] A custom TMS layer to spot missing `ref` tags; @pratikyadav
- [ ] Better documentation of workflow to scale up the team; @pratikyadav


Closing here.
