### ISSUE TITLE
HOT Mapping - Validating: In response Mexican earthquake

### ISSUE THREAD

**Issue by piligab** [mapbox/mapping#342]
On Tuesday 19 September 2017, a powerful earthquake (magnitude 7.1) jolted central Mexico, cracking building facades and scattering rubble on streets in the capital on the anniversary of a devastating 1985 quake. Its epicenter was near the Puebla state town of Raboso, about 76 miles southeast of Mexico City.

We will be mapping the buildings and highways in Mexico as part of Humanitarian OpenStreetMap Teams'(HOT) disaster mapping efforts.

### Tasking Manager - Urgent
- [x] https://tasks.hotosm.org/project/3648#bottom
- [x] https://tasks.hotosm.org/project/3601#bottom
- [x] https://tasks.hotosm.org/project/3646#bottom

### Mapping sources
- Bing imagery and DigitalGlobe imagery
- JOSM 

#### Task Coverage 
- Izúcar de Matamoros (center), Puebla
- Atlixco, Puebla
- Izúcar de Matamoros (south), Puebla

#### Activities
- Go through the instructions before you start. 
- Valid all the roads and buildings in the tasks using Bing imagery

#### - Task #3648
![image](https://user-images.githubusercontent.com/19536044/33028942-358f5bac-cde5-11e7-991a-fe6a2c20fa46.png)

- Right now, the task is 98% mapped and 64% validated. So let's all the roads and buildings using Bing imagery and validate 100%. 
![image](https://user-images.githubusercontent.com/19536044/33029064-977aa146-cde5-11e7-9db4-7489685816b6.png)

#### - Task #3601
![image](https://user-images.githubusercontent.com/19536044/33028889-199b2a16-cde5-11e7-9ebe-57532fdb8871.png)

- Right now, the task is 96% mapped and 42% validated. So let's all the roads and buildings using Bing imagery and validate 100%. 
![image](https://user-images.githubusercontent.com/19536044/33029168-df432cdc-cde5-11e7-99ea-c4130c77fce3.png)

#### - Task #3646
![image](https://user-images.githubusercontent.com/19536044/33209700-2c28caaa-d0e5-11e7-96cc-1b776bd26597.png)

- Right now, the task is 96% mapped and 77% validated. So let's all the roads and buildings using Bing imagery and validate 100%. 

cc @maning @Rub21

**Comment by piligab** [comment]
Today @mapbox/peru-office we worked on the first task (3648), we validated up to **87%.**
![image](https://user-images.githubusercontent.com/19536044/33048956-af08c356-ce2b-11e7-863c-20dabf15733a.png)

In this task we don't advanced very fast because we had some difficulties such as:
- There aren't good imagery
- The imagery used were Bing and DigitalGlobe, but between both imagery there is a desfase, there are some user that they use bing o DigitalGlobe. We verified wath imagery they have used and we do validating with those imagery.
![image](https://user-images.githubusercontent.com/19536044/33049381-d0fbee1e-ce2d-11e7-80bc-cc0b8530726f.png)
![image](https://user-images.githubusercontent.com/19536044/33049392-e3023014-ce2d-11e7-8fda-99cd85e2f53b.png)

cc. @Rub21

**Comment by piligab** [comment]
During this week @mapbox/peru-office was working on mapping and validating.

We finished tasks  [#3648](https://tasks.hotosm.org/project/3648#bottom) and [#3601]( https://tasks.hotosm.org/project/3601#bottom) :rocket: :tada: 

![image](https://user-images.githubusercontent.com/19536044/33210246-70ebd9b4-d0e7-11e7-92b4-7bcd42e7025d.png)

Now we are working on [#3646](https://tasks.hotosm.org/project/3646#bottom) 
![image](https://user-images.githubusercontent.com/19536044/33210313-ae90ac90-d0e7-11e7-9127-9e769c50ed2f.png)

**Comment by piligab** [comment]
:clap: good work @mapbox/peru-office. We finished all task about Mexican earthquake.
- [x] https://tasks.hotosm.org/project/3648#bottom
- [x] https://tasks.hotosm.org/project/3601#bottom
- [x] https://tasks.hotosm.org/project/3646#bottom
![image](https://user-images.githubusercontent.com/19536044/33249876-f17961e0-d2fa-11e7-81a7-e7320addcd87.png)
cc. @Rub21

**Comment by piligab** [comment]
There is an other urgent task :point_right: https://tasks.hotosm.org/project/3549

![image](https://user-images.githubusercontent.com/19536044/33403013-ae418f7c-d52c-11e7-9c2a-2179d3ebf83d.png)

![image](https://user-images.githubusercontent.com/19536044/33403051-d08a7dc8-d52c-11e7-936f-31480f0e8016.png)

@mapbox/peru-office Let's start mapping :rocket:

**Comment by piligab** [comment]
We finished :point_up: :100: % this task [#3549](https://tasks.hotosm.org/project/3549) 

![image](https://user-images.githubusercontent.com/19536044/33555792-a45febc4-d8cf-11e7-9c58-5926f129d0f2.png)

:clap: Good work everyone :tada: .
